// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3qYRPH1K70Xo-Nae9FWws4WPi6N-1RE8',
    appId: '1:913708100804:web:a6e803fa80c4db94f0ed91',
    messagingSenderId: '913708100804',
    projectId: 'vulnerability-finder',
    authDomain: 'vulnerability-finder.firebaseapp.com',
    storageBucket: 'vulnerability-finder.firebasestorage.app',
    measurementId: 'G-8CCMSYEZRT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiFLYHE5aBSMUxKj4l88l3f9SeN3F0k7g',
    appId: '1:913708100804:ios:895b3cf1d3d1172ff0ed91',
    messagingSenderId: '913708100804',
    projectId: 'vulnerability-finder',
    storageBucket: 'vulnerability-finder.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3qYRPH1K70Xo-Nae9FWws4WPi6N-1RE8',
    appId: '1:913708100804:web:36c21e52aec99cc2f0ed91',
    messagingSenderId: '913708100804',
    projectId: 'vulnerability-finder',
    authDomain: 'vulnerability-finder.firebaseapp.com',
    storageBucket: 'vulnerability-finder.firebasestorage.app',
    measurementId: 'G-FPRKCBQHPH',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvbvzrIoGe1ed5ml8yeM01--PBNlO4WTQ',
    appId: '1:272295707058:ios:7055d9753046fca25ce4ab',
    messagingSenderId: '272295707058',
    projectId: 'event-notifs',
    storageBucket: 'event-notifs.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdbvS74LkYKO8APDmuflR-MdOLKyjIvf4',
    appId: '1:272295707058:android:a319880f046962165ce4ab',
    messagingSenderId: '272295707058',
    projectId: 'event-notifs',
    storageBucket: 'event-notifs.firebasestorage.app',
  );

}