// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuAWMPNrJorFLzW15zOVtEMqdZd53u6hw',
    appId: '1:272295707058:web:8a0f3383fef272c55ce4ab',
    messagingSenderId: '272295707058',
    projectId: 'event-notifs',
    authDomain: 'event-notifs.firebaseapp.com',
    storageBucket: 'event-notifs.firebasestorage.app',
    measurementId: 'G-H3N40Z6TDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdbvS74LkYKO8APDmuflR-MdOLKyjIvf4',
    appId: '1:272295707058:android:a319880f046962165ce4ab',
    messagingSenderId: '272295707058',
    projectId: 'event-notifs',
    storageBucket: 'event-notifs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvbvzrIoGe1ed5ml8yeM01--PBNlO4WTQ',
    appId: '1:272295707058:ios:7055d9753046fca25ce4ab',
    messagingSenderId: '272295707058',
    projectId: 'event-notifs',
    storageBucket: 'event-notifs.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvbvzrIoGe1ed5ml8yeM01--PBNlO4WTQ',
    appId: '1:272295707058:ios:7055d9753046fca25ce4ab',
    messagingSenderId: '272295707058',
    projectId: 'event-notifs',
    storageBucket: 'event-notifs.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuAWMPNrJorFLzW15zOVtEMqdZd53u6hw',
    appId: '1:272295707058:web:5b989c42f304b93b5ce4ab',
    messagingSenderId: '272295707058',
    projectId: 'event-notifs',
    authDomain: 'event-notifs.firebaseapp.com',
    storageBucket: 'event-notifs.firebasestorage.app',
    measurementId: 'G-0P1G6W38FB',
  );
}
